zuul:
  prefix: /api
  routes: 
    eureka-client-1:
      path: /client1/**
      serviceId: EUREKA-CLIENT-1
    eureka-client-2:
      path: /client2/**
      serviceId: EUREKA-CLIENT-2
    eureka-client-3:
      path: /client3/**
      serviceId: EUREKA-CLIENT-3
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8079

spring:
  application:
    name: zuul-service
    
    hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 80000

